spring.application.name=mecaniqa-cloud

server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mecaniqa}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:mecaniqa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mecaniqa123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
